2024-01-05 19:58:28,190 INFO    StreamThr :181039 [internal.py:wandb_internal():86] W&B internal server running at pid: 181039, started at: 2024-01-05 19:58:28.189594
2024-01-05 19:58:28,192 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status
2024-01-05 19:58:28,193 INFO    WriterThread:181039 [datastore.py:open_for_write():85] open: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/run-b8omjk0k.wandb
2024-01-05 19:58:28,194 DEBUG   SenderThread:181039 [sender.py:send():382] send: header
2024-01-05 19:58:28,194 DEBUG   SenderThread:181039 [sender.py:send():382] send: run
2024-01-05 19:58:28,446 INFO    SenderThread:181039 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/files
2024-01-05 19:58:28,446 INFO    SenderThread:181039 [sender.py:_start_run_threads():1136] run started: b8omjk0k with start time 1704484707.30675
2024-01-05 19:58:28,457 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: check_version
2024-01-05 19:58:28,458 DEBUG   SenderThread:181039 [sender.py:send_request():409] send_request: check_version
2024-01-05 19:58:28,558 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: run_start
2024-01-05 19:58:28,559 DEBUG   HandlerThread:181039 [system_info.py:__init__():32] System info init
2024-01-05 19:58:28,559 DEBUG   HandlerThread:181039 [system_info.py:__init__():47] System info init done
2024-01-05 19:58:28,559 INFO    HandlerThread:181039 [system_monitor.py:start():194] Starting system monitor
2024-01-05 19:58:28,559 INFO    SystemMonitor:181039 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-05 19:58:28,560 INFO    HandlerThread:181039 [system_monitor.py:probe():214] Collecting system info
2024-01-05 19:58:28,560 INFO    SystemMonitor:181039 [interfaces.py:start():190] Started cpu monitoring
2024-01-05 19:58:28,561 INFO    SystemMonitor:181039 [interfaces.py:start():190] Started disk monitoring
2024-01-05 19:58:28,562 INFO    SystemMonitor:181039 [interfaces.py:start():190] Started gpu monitoring
2024-01-05 19:58:28,563 INFO    SystemMonitor:181039 [interfaces.py:start():190] Started memory monitoring
2024-01-05 19:58:28,564 INFO    SystemMonitor:181039 [interfaces.py:start():190] Started network monitoring
2024-01-05 19:58:28,573 DEBUG   HandlerThread:181039 [system_info.py:probe():196] Probing system
2024-01-05 19:58:28,573 DEBUG   HandlerThread:181039 [system_info.py:_probe_git():181] Probing git
2024-01-05 19:58:28,580 DEBUG   HandlerThread:181039 [system_info.py:_probe_git():189] Probing git done
2024-01-05 19:58:28,580 DEBUG   HandlerThread:181039 [system_info.py:probe():244] Probing system done
2024-01-05 19:58:28,580 DEBUG   HandlerThread:181039 [system_monitor.py:probe():223] {'os': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-01-05T19:58:28.573210', 'startedAt': '2024-01-05T19:58:22.996472', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/yashchks87/plant_pathology.git', 'commit': 'e7ca672c0321a4e059c320454bd1c72cda725cf4'}, 'email': None, 'root': '/home/ubuntu/plant_pathology', 'host': '129-213-82-104', 'username': 'ubuntu', 'executable': '/usr/bin/python3', 'cpu_count': 30, 'cpu_count_logical': 30, 'cpu_freq': {'current': 2449.9980000000005, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 496.0301856994629, 'used': 31.833934783935547}}, 'gpu': 'NVIDIA A100-SXM4-40GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA A100-SXM4-40GB', 'memory_total': 42949672960}], 'memory': {'total': 196.56491088867188}}
2024-01-05 19:58:28,580 INFO    HandlerThread:181039 [system_monitor.py:probe():224] Finished collecting system info
2024-01-05 19:58:28,580 INFO    HandlerThread:181039 [system_monitor.py:probe():227] Publishing system info
2024-01-05 19:58:28,580 DEBUG   HandlerThread:181039 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-01-05 19:58:28,580 DEBUG   HandlerThread:181039 [system_info.py:_save_pip():68] Saving pip packages done
2024-01-05 19:58:28,581 INFO    HandlerThread:181039 [system_monitor.py:probe():229] Finished publishing system info
2024-01-05 19:58:28,582 DEBUG   SenderThread:181039 [sender.py:send():382] send: files
2024-01-05 19:58:28,582 INFO    SenderThread:181039 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-01-05 19:58:28,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:58:28,591 DEBUG   SenderThread:181039 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:58:28,635 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:58:28,864 DEBUG   SenderThread:181039 [sender.py:send():382] send: telemetry
2024-01-05 19:58:28,936 INFO    wandb-upload_0:181039 [upload_job.py:push():131] Uploaded file /tmp/tmp5giz_ch0wandb/gwa5buzw-wandb-metadata.json
2024-01-05 19:58:29,447 INFO    Thread-25 :181039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/files/wandb-metadata.json
2024-01-05 19:58:29,448 INFO    Thread-25 :181039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/files/requirements.txt
2024-01-05 19:58:29,448 INFO    Thread-25 :181039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/files/output.log
2024-01-05 19:58:31,447 INFO    Thread-25 :181039 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/files/output.log
2024-01-05 19:58:33,884 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:38,885 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:43,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:58:43,591 DEBUG   SenderThread:181039 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:58:43,634 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:58:44,677 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:49,678 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:54,678 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:58,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:58:58,591 DEBUG   SenderThread:181039 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:58:58,638 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:58:59,708 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:58:59,818 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:58:59,818 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:00,875 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:59:00,875 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:02,965 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:59:02,965 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:02,965 INFO    SenderThread:181039 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-01-05 19:59:07,033 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:59:07,033 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:13,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:59:13,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:59:17,090 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:59:17,090 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:19,591 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:24,594 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:28,564 DEBUG   SystemMonitor:181039 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-05 19:59:28,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:59:33,593 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:34,841 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:59:34,841 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:59:38,594 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:43,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:59:48,595 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:53,596 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 19:59:58,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:00:03,597 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:06,985 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 20:00:06,985 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 20:00:08,598 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:13,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:00:18,599 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:23,600 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:28,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:00:33,601 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:38,602 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:43,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:00:48,603 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:53,604 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:00:58,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:01:03,605 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:01:08,606 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:01:13,592 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 20:01:18,608 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:01:23,608 DEBUG   HandlerThread:181039 [handler.py:handle_request():146] handle_request: keepalive
2024-01-05 20:01:26,960 ERROR   SenderThread:181039 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 20:01:26,960 ERROR   SenderThread:181039 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 20:01:26,960 INFO    HandlerThread:181039 [handler.py:finish():866] shutting down handler
2024-01-05 20:01:26,960 INFO    HandlerThread:181039 [system_monitor.py:finish():203] Stopping system monitor
2024-01-05 20:01:26,961 DEBUG   SystemMonitor:181039 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-05 20:01:26,962 INFO    HandlerThread:181039 [interfaces.py:finish():202] Joined cpu monitor
2024-01-05 20:01:26,962 INFO    HandlerThread:181039 [interfaces.py:finish():202] Joined disk monitor
2024-01-05 20:01:26,962 DEBUG   SystemMonitor:181039 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-05 20:01:26,962 INFO    WriterThread:181039 [datastore.py:close():294] close: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_195822-b8omjk0k/run-b8omjk0k.wandb
2024-01-05 20:01:27,036 INFO    HandlerThread:181039 [interfaces.py:finish():202] Joined gpu monitor
2024-01-05 20:01:27,036 INFO    HandlerThread:181039 [interfaces.py:finish():202] Joined memory monitor
2024-01-05 20:01:27,036 INFO    HandlerThread:181039 [interfaces.py:finish():202] Joined network monitor
2024-01-05 20:01:27,392 ERROR   StreamThr :181039 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2212, in upsert_run
    response = self.gql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 540, in debounce
    self._maybe_update_config(always=final)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 517, in _maybe_update_config
    self._debounce_config()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 546, in _debounce_config
    self._api.upsert_run(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run yashchks87/plant_pathology/b8omjk0k was previously created and deleted; try a new run name (Error 409: Conflict)
