2024-01-06 20:56:36,383 INFO    MainThread:37543 [wandb_setup.py:_flush():68] Configure stats pid to 37543
2024-01-06 20:56:36,383 INFO    MainThread:37543 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/.config/wandb/settings
2024-01-06 20:56:36,383 INFO    MainThread:37543 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/Documents/plant_pathology/notebooks/wandb/settings
2024-01-06 20:56:36,383 INFO    MainThread:37543 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-01-06 20:56:36,384 INFO    MainThread:37543 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-06 20:56:36,384 INFO    MainThread:37543 [wandb_init.py:_log_setup():476] Logging user logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240106_205636-2v6g1whn/logs/debug.log
2024-01-06 20:56:36,384 INFO    MainThread:37543 [wandb_init.py:_log_setup():477] Logging internal logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240106_205636-2v6g1whn/logs/debug-internal.log
2024-01-06 20:56:36,384 INFO    MainThread:37543 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9ce55223d0>
2024-01-06 20:56:36,384 INFO    MainThread:37543 [wandb_init.py:init():516] calling init triggers
2024-01-06 20:56:36,385 INFO    MainThread:37543 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'model_name': 'incep_v1', 'dataset_name': 'plant_pathology', 'epochs': 100, 'batch_size': 512, 'num_workers': 10, 'learning_rate': 0.001, 'optimizer': 'Adam', 'weights_path': '../../weights/incep_v1_hflip_rotate_jitter_cut_out_v2/', 'normalize': True, 'horizontal_flip': True, 'random_rotation': True, 'color_jitter': True, 'brightness': 0.5, 'contrast': 0.5, 'saturation': 0.5, 'hue': 0.5, 'cut_out_dict': {'size_of_cutout': 24, 'num_of_cutout_holes': 4}}
2024-01-06 20:56:36,385 INFO    MainThread:37543 [wandb_init.py:init():569] starting backend
2024-01-06 20:56:36,385 INFO    MainThread:37543 [wandb_init.py:init():573] setting up manager
2024-01-06 20:56:36,387 INFO    MainThread:37543 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-06 20:56:36,388 INFO    MainThread:37543 [wandb_init.py:init():580] backend started and connected
2024-01-06 20:56:36,394 INFO    MainThread:37543 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2024-01-06 20:56:36,395 INFO    MainThread:37543 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-06 20:56:36,395 INFO    MainThread:37543 [wandb_init.py:init():658] updated telemetry
2024-01-06 20:56:36,414 INFO    MainThread:37543 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2024-01-06 20:56:36,596 INFO    MainThread:37543 [wandb_run.py:_on_init():2000] communicating current version
2024-01-06 20:56:36,646 INFO    MainThread:37543 [wandb_run.py:_on_init():2004] got version response upgrade_message: "wandb version 0.16.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-06 20:56:36,646 INFO    MainThread:37543 [wandb_init.py:init():728] starting run threads in backend
2024-01-06 20:56:36,928 INFO    MainThread:37543 [wandb_run.py:_console_start():1980] atexit reg
2024-01-06 20:56:36,928 INFO    MainThread:37543 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2024-01-06 20:56:36,928 INFO    MainThread:37543 [wandb_run.py:_redirect():1903] Wrapping output streams.
2024-01-06 20:56:36,928 INFO    MainThread:37543 [wandb_run.py:_redirect():1925] Redirects installed.
2024-01-06 20:56:36,929 INFO    MainThread:37543 [wandb_init.py:init():765] run started, returning control to user process
2024-01-06 20:56:52,877 INFO    MainThread:37543 [wandb_init.py:_pause_backend():389] pausing backend
2024-01-06 20:56:52,878 INFO    MainThread:37543 [jupyter.py:save_ipynb():378] not saving jupyter notebook
